name: "CMake on Ubuntu Linux, AMD64 and ARM64"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        build_type: [Release]
        c_compiler: [gcc]
        include:
          - os: ubuntu-24.04
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-24.04-arm
            c_compiler: gcc
            cpp_compiler: g++

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Setup python for helper scripts
      uses: actions/setup-python@v5 
      with:
        python-version: '3.11'

    - name: Run python payload
      run: |
        python -m pip install requests pyfiglet
        python -m pip install NekoMimi
        python "${{ github.workspace }}/workflow.py" "${{ github.workspace }}"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NReg-Nightly-${{ matrix.os }}
        path: build
        if-no-files-found: error
        retention-days: 0
        compression-level: 6
        overwrite: true
        include-hidden-files: false
